version: '3.1'

services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: PINGPONGDB
      POSTGRES_USER: ADMIN
      POSTGRES_PASSWORD: ADMIN
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  data:
networks:
  app-network:
    driver: bridge

